---

- name: add prerequisites
  apt: name={{ item }} update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: add source for apt
  template: src=docker.list dest=/etc/apt/sources.list.d/docker.list

- name: istall docker
  apt: name=docker-engine update_cache=yes allow_unauthenticated=yes
  notify: start docker